server:
  port: 8080

management:
  health:
    defaults:
      enabled: false
  security:
    health:
      enabled: false

logging:
  level:
    root: DEBUG

spring:
  application:
    name: search-service
  profiles:
    active: local
es:
  cluster-name: dlsp
  nodes: 127.0.0.1:9202,127.0.0.1:9302,127.0.0.1:9402
  bulk-actions: 400
---
spring:
  profiles: beta

---
spring:
  profiles: release
