server:
  port: 8761

spring:
  application:
    name: eureka-server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl.defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
---
spring:
  profiles: eureka-1
server:
  port: 8762
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/
---
spring:
  profiles: eureka-2
server:
  port: 8763
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
